name: "batch_size_exp_8x160000x256"
lr: 1e-3
weight_decay: 1e-4
betas: [0.9, 0.999]
eps: 1e-8
train_dataset_path: "./data/TinyStoriesV2-GPT4-train.txt"
test_dataset_path: "./data/TinyStoriesV2-GPT4-valid.txt"
cache_dir: "./cache/"
special_tokens: ["<|endoftext|>"]
num_epoch: 160000
batch_size: 
  train: 8
  eval: 64
lr_schedule:
  type: "cosine_annealing" 
  params:
    alpha_min: 1e-5
    Tw: 16000
    Tc: 160000
model_saved_interval: 16000
model_saved_path: "./models/"
gradient_clipping:
  enable: true
  max_l2_norm: 1.0
wandb:
  project: cs336_assignment1_jiacheng
  entity: jiacheng-luo
  run_id: "0p62fxqn"